name: CD Pipeline

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted  
    
    steps:
      - name: Debugging
        run: ls 
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-app
          path: ./next/next-deploy.zip
      
      - name: Unzip artifact
        run: unzip next-deploy.zip -d .

      - name: Install dependencies
        run: npm ci --force  

      - name: Start application
        run: |
          npm install -g pm2   
          pm2 delete next-app || true   
          pm2 start npm --name "next-app" -- run start
