name: CD Pipeline

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted  
    
    steps:

      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ciPipeline.yml
          name: next-app
          # path: ./
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip artifact
        run: unzip deploy.zip -d .

      - name: Install dependencies
        run: npm ci --force  

      - name: Start application
        run: |
          npm install -g pm2   
          pm2 delete next-app || true   
          pm2 start npm --name "next-app" -- run start
