name: CD Pipeline

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted  
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          # workflow: ciPipeline.yml
          name: nextapp
          # path: ./
          github-token: ${{ secrets.SECRET_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Unzip artifact
        run: tar -xzf deploy.tar.gz -C .

      - name: Install dependencies
        run: npm ci --force  

      - name: Ensure pm2 installed
        run: npm install -g pm2

      - name: Restart application with pm2
        run: |
          pm2 delete next-app || true
          pm2 start npm --name "next-app" -- run start -- -H 0.0.0.0 -p 3000
          pm2 save
